name: cicd

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # TODO matrix of python versions
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('tests/requirements.txt') }}

      - name: Install poetry
        run: pip install poetry==1.5.1

      - name: Install code
        run: poetry install

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

  cd:
    # Only run this job if the "ci" job passes
    needs: ci

    # Only run this job if new work is pushed to the "main" branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pip install poetry==1.5.1

      - name: Install code
        run: poetry install

      - name: Semantic Release
        id: release
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          poetry run semantic-release publish -D commit_author='github-actions <action@github.com>' 2> out.txt
          echo "::set-output name=semrel::$(cat out.txt)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish to Test PyPI
        uses: JRubics/poetry-publish@v1.10
        if: ${{ !contains(join(steps.release.outputs.*), 'No release will be made') }}
        with:
          pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
        env:
          SEM_RELEASE_STATUS: ${{ join(steps.release.outputs.*) }}

      - name: Test install from Test PyPI
        if: ${{ !contains(join(steps.release.outputs.*), 'No release will be made') }}
        run: |
          pip install \
          --index-url https://test.pypi.org/simple/ \
          --extra-index-url https://pypi.org/simple \
          flask-cognito-lib

      - name: Build and publish to PyPI
        if: ${{ !contains(join(steps.release.outputs.*), 'No release will be made') }}
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
