name: docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('tests/requirements.txt') }}

      - name: Install poetry
        run: pip install poetry==1.1.12
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install code
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Publish to Github pages
        run: poetry run mkdocs gh-deploy --force
